### ISSUE TITLE
Signup & login pages 

### ISSUE THREAD

**Issue by anjalisoni3655** [girlscript/Star-in-me#14]
-  signup and login options ( Google, linkedin, Facebook)
 - OTP verification
- signup/login confirmation page
- manual signup page, create password/ forget password.

Wireframes are available in the signup folder in the google drive link.

It will require Firebase authentication along with the firestore to store the user details.

Interested ones having prior knowledge about this or willing to learn, please comment below in the format " please assign this issue to me, willing to work on it".

For any queries  regarding this issue/task reply to this thread only.

We will need 2-3 people for this part, so that they all can work together.

**Comment by Shubham-1105** [comment]
please assign this issue to me, willing to work on it

**Comment by shivanigupta19** [comment]
Please assign me this issue.

**Comment by KhyatiSaini** [comment]
I'm also willing to work on this issue

**Comment by Akshima-Ghai** [comment]
please assign this issue to me, willing to work on it

**Comment by asmita08** [comment]
Willing to work, please assign me this issue.

**Comment by anjalisoni3655** [comment]
> please assign this issue to me, willing to work on it

assigning this issue to @Shubham-1105 @KhyatiSaini @shivanigupta19

**Comment by anjalisoni3655** [comment]
start working together all three of you. Divide the work among yourselves.
