### ISSUE TITLE
199 User Profile after connecting

### ISSUE THREAD

**Issue by microaditi** [girlscript/Star-in-me#9]

**Comment by microaditi** [comment]
User Profile After Logging in/ Signup

![199 user_profile_Mobile_After connecting_Unfollow@2x](https://user-images.githubusercontent.com/43278204/92634461-f8986b00-f2f1-11ea-9cad-1700fa5f5822.png)

**Comment by anjalisoni3655** [comment]
ok, it will be assigned to you, but we have to go step by step. First the login and signup screen need to be done, may be you can try making this UI in your local device and then just do the same for this app. @microaditi
